# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  update-code:
    name: Git Update
    runs-on: ubuntu-latest

    steps:
      - name: Update Code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: dougmabelmercer.ca
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd ${{ secrets.PROD_PATH }}
            git pull

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: update-code
    
    steps:
    - name: Deploy Server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: dougmabelmercer.ca
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script: |
          cd ${{ secrets.PROD_PATH }}
          ./script/deploy-server.sh

  deploy-client:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: update-code

    steps:
      - name: Deploy Client
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: dougmabelmercer.ca
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd ${{ secrets.PROD_PATH }}
            ./script/deploy-client.sh
