# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Production Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Production Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          host: dougmabelmercer.ca
          port: 22
          script_stop: true
          script: |
            cd /opt/web-apps/dougmabelmercer.ca
            git pull
            ./script/deploy.sh
