# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  ROOT_DIR: ${{ secrets.PROD_PATH }}
  username: ${{ secrets.PROD_USER }}
  ssh_key: ${{ secrets.PROD_KEY }}
  host: dougmabelmercer.ca
  port: 22

jobs:
  update-code:
    name: Git Update
    runs-on: ubuntu-latest

    steps:
      - name: Update Code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ host }}
          port: ${{ port }}
          username: ${{ username }}
          key: ${{ key }}
          envs: ROOT_DIR
          script_stop: true
          script: |
            cd $ROOT_DIR
            git pull

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs: update-code

    steps:
    - name: Deploy Server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ host }}
        port: ${{ port }}
        username: ${{ username }}
        key: ${{ key }}
        envs: ROOT_DIR
        script_stop: true
        script: |
          cd $ROOT_DIR
          ./script/deploy-server.sh

  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    needs: update-code

    steps:
      - name: Deploy Client
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ host }}
          port: ${{ port }}
          username: ${{ username }}
          key: ${{ key }}
          envs: ROOT_DIR
          script_stop: true
          script: |
            cd $ROOT_DIR
            ./script/deploy-client.sh
